# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqtdesigner.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InstrumentWidget(object):
    def setupUi(self, InstrumentWidget):
        InstrumentWidget.setObjectName("InstrumentWidget")
        InstrumentWidget.resize(580, 142)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(InstrumentWidget.sizePolicy().hasHeightForWidth())
        InstrumentWidget.setSizePolicy(sizePolicy)
        InstrumentWidget.setMinimumSize(QtCore.QSize(50, 2))
        InstrumentWidget.setMaximumSize(QtCore.QSize(16777215, 142))
        self.verticalLayout = QtWidgets.QVBoxLayout(InstrumentWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(InstrumentWidget)
        self.tableWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setToolTipDuration(-7)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignBottom)
        font = QtGui.QFont()
        font.setFamily("Futura Bk BT")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignBottom)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        item.setFont(font)
        self.tableWidget.setItem(0, 1, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(53)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(14)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(23)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(25)
        self.verticalLayout.addWidget(self.tableWidget)
        self.rangeGraph = QtWidgets.QGraphicsView(InstrumentWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.rangeGraph.sizePolicy().hasHeightForWidth())
        self.rangeGraph.setSizePolicy(sizePolicy)
        self.rangeGraph.setBaseSize(QtCore.QSize(0, 10))
        self.rangeGraph.setLineWidth(0)
        self.rangeGraph.setObjectName("rangeGraph")
        self.verticalLayout.addWidget(self.rangeGraph)

        self.retranslateUi(InstrumentWidget)
        QtCore.QMetaObject.connectSlotsByName(InstrumentWidget)

    def retranslateUi(self, InstrumentWidget):
        _translate = QtCore.QCoreApplication.translate
        InstrumentWidget.setWindowTitle(_translate("InstrumentWidget", "Widget"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("InstrumentWidget", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("InstrumentWidget", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("InstrumentWidget", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("InstrumentWidget", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("InstrumentWidget", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("InstrumentWidget", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("InstrumentWidget", "New Column"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("InstrumentWidget", "1234"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

